name: Hexo Deploy

on:
  push:
    branches:
      - main  # 你部署的分支，通常是 main 或 master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Hexo
      run: npm install hexo-cli -g

    - name: Install dependencies
      run: npm install

    - name: Generate site
      run: hexo generate

    - name: Deploy to GitHub Pages
      run: hexo deploy
